import { access, mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

import type { ResolvedIconPackage } from "./resolve-package"

interface SyncIconkitTypeFileOptions {
  outputFile?: string | false
  resolvedPackage: ResolvedIconPackage
  root: string
}

export async function syncIconkitTypeFile({
  outputFile,
  resolvedPackage,
  root,
}: SyncIconkitTypeFileOptions): Promise<string | null> {
  const filePath = await resolveTypeFilePath(root, outputFile)
  if (!filePath) {
    return null
  }

  const nextContent = renderIconkitTypeFile(resolvedPackage)
  const currentContent = await readIfExists(filePath)

  if (currentContent === nextContent) {
    return filePath
  }

  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, nextContent, "utf8")
  return filePath
}

export function renderIconkitTypeFile(resolvedPackage: ResolvedIconPackage): string {
  const iconNames = [...resolvedPackage.iconsByName.keys()].sort((left, right) => left.localeCompare(right))
  const iconNameUnion =
    iconNames.length === 0
      ? "    iconName: never\n"
      : `    iconName:\n${iconNames.map((iconName) => `      | ${JSON.stringify(iconName)}`).join("\n")}\n`

  return `// This file is auto-generated by iconkit.
// It binds iconkit/compile to the currently selected package:
// ${resolvedPackage.packageName}

import "iconkit/compile"

declare module "iconkit/compile" {
  interface IconkitCompileTypeRegistry {
${iconNameUnion}  }
}

export {}
`
}

async function resolveTypeFilePath(root: string, outputFile: string | false | undefined): Promise<string | null> {
  if (outputFile === false) {
    return null
  }

  if (typeof outputFile === "string") {
    return path.resolve(root, outputFile)
  }

  const srcDir = path.join(root, "src")

  try {
    await access(srcDir)
    return path.join(srcDir, "iconkit.generated.d.ts")
  } catch {
    return path.join(root, "iconkit.generated.d.ts")
  }
}

async function readIfExists(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, "utf8")
  } catch {
    return null
  }
}
